# Homebrew cask for butterPDF. GENERATED by `butterpdf bake` — the INITIAL
# cask to seed your tap (homebrew-<tap>); macos.yml's bump action maintains the
# version + sha256 thereafter (docs/BAKING.md §5). Committed form is version-free.
cask "butterpdf" do
  version "0.0.0"
  sha256 :no_check

  url "https://github.com/wolfgangwarehaus/butterpdf/releases/download/v#{version}/butterpdf-#{version}-macos.dmg"
  name "butterPDF"
  desc "Open, fill, sign, done — a fast frosted PDF tool."
  homepage "https://github.com/wolfgangwarehaus/butterpdf"

  app "butterpdf.app"

  zap trash: [
    "~/Library/Preferences/com.wolfgangwarehaus.butterpdf.plist",
    "~/Library/Application Support/butterPDF",
    "~/Library/Saved Application State/com.wolfgangwarehaus.butterpdf.savedState",
  ]
end
