"""PyInstaller entry shim for the frozen bundle. GENERATED by `butterpdf bake`.

A bare module that calls the configured entry point (butterpdf.app:main). The
freeze targets this file (not ``-m butterpdf``) so PyInstaller's analysis
has a concrete script to start from.
"""
from butterpdf.app import main

if __name__ == "__main__":
    main()
